# Generated by Django 4.1 on 2023-01-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_invoice_discount_alter_invoicedetail_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_unit',
            field=models.IntegerField(default=0),
        ),
    ]
